baseURL: "/"
languageCode: "en-us"
title: "The Howlers"
theme: "template"
outputs:
  home: [ "HTML", "REDIRECTS" ]
pygmentsCodefences: true
pygmentsStyle: "pygments"
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: native
    tabWidth: 4
menu:
  docs:
params:
  twitter_url: "https://twitter.com"
  github_url: "https://github.com"
  slack_url: ""
  googlegroups_url: "https://groups.google.com"
  github_base_url: "https://github.com/vmware/"
  use_advanced_docs: true
  docs_right_sidebar: true
  docs_search: false
  docs_search_index_name: index_name
  docs_search_api_key: api_key
  docs_versioning: true
  docs_latest: v0.0.1
  docs_versions:
    - v0.0.1
mediaTypes:
  "text/netlify":
    delimiter: ""
outputFormats:
  REDIRECTS:
    mediaType: "text/netlify"
    baseName: "_redirects"